# **Pytorch**

In [ ]:
import torch

print(torch.__version__)

if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available")

# print(torch.cuda.get_device_name(0))

2.10.0+cpu
CUDA is not available


## **Tensors**

In [ ]:
tensor1 = torch.empty(
    2, 3
)  # allocate memory for you and show the value which are already in memory
print(type(tensor1))
print(torch.zeros(2, 4))
print(torch.ones(2, 3))
print(torch.rand(2, 3))
torch.manual_seed(100)
print(torch.rand(2, 3))
print(torch.tensor([[1, 2, 3], [4, 5, 6]]))
print(torch.eye(5))
print(torch.linspace(0, 10, 20))
print(f"{torch.full((3, 3), 5)}")

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6729, 0.4087, 0.5757],
        [0.2856, 0.3570, 0.1968]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## **Tensor's Shape**

In [ ]:
tensor1.shape
print(torch.empty_like(tensor1))
print(torch.zeros_like(tensor1))

## **Tensors in GPU**

In [ ]:
torch.cuda.is_available()
device = torch.device("cuda")
print(device)
torch.rand((10, 12), device=device)

## **CPU VS GPU**

In [ ]:
import time

cpu_matrix_1 = torch.rand(10000, 10000)
cpu_matrix_2 = torch.rand(10000, 10000)
start_time = time.time()
result_cpu = cpu_matrix_1.matmul(cpu_matrix_2)
end_time = time.time() - start_time
print(end_time)

matric_gpu_1 = cpu_matrix_1.to(device=device)
matric_gpu_2 = cpu_matrix_2.to(device=device)
start_time = time.time()
result_gpu = matric_gpu_1.matmul(matric_gpu_2)
end_time = time.time() - start_time
print(end_time)

# **Pytorch Autograd**

In [ ]:
x = torch.tensor(3.0, requires_grad=True)
print(x)
y = x**9 + 5 * x**5 + 3
print(y)
print(y.backward())
print(x.grad)
z = torch.sin(y)
print(f"x:{x}")
print(f"y:{y}")
print(f"Z:{z}")
z.backward()
print(x.grad)

x = torch.tensor(3.0, requires_grad=True)

y = x**9 + 5 * x**5 + 3
z = torch.sin(y)

z.backward()

print(x.grad)


## **Pytorch training Pipelines**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder


In [ ]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
)
df.head()
print(df.shape)
df.isnull().sum()
df.describe()
df.info()
df.columns

(569, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se    

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [ ]:
df.drop(columns=["Unnamed: 32", "id"], inplace=True)

In [ ]:
print(df.head())
print(df.info())
print(df.describe())
print(df.head())
print(df.info())
print(df.describe())


  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactne

## **Splitting the dataa**

In [ ]:
"""
Use loc when you mean “rows/cols with these names” (and for boolean filtering).
Use iloc when you mean “the nth row/column” regardless of labels.
"""

x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=["diagnosis"]), df["diagnosis"], test_size=0.2, random_state=42
)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
print(x_train)
print(x_test)


[[-1.44075296 -0.43531947 -1.36208497 ...  0.9320124   2.09724217
   1.88645014]
 [ 1.97409619  1.73302577  2.09167167 ...  2.6989469   1.89116053
   2.49783848]
 [-1.39998202 -1.24962228 -1.34520926 ... -0.97023893  0.59760192
   0.0578942 ]
 ...
 [ 0.04880192 -0.55500086 -0.06512547 ... -1.23903365 -0.70863864
  -1.27145475]
 [-0.03896885  0.10207345 -0.03137406 ...  1.05001236  0.43432185
   1.21336207]
 [-0.54860557  0.31327591 -0.60350155 ... -0.61102866 -0.3345212
  -0.84628745]]
[[-0.46649743 -0.13728933 -0.44421138 ... -0.19435087  0.17275669
   0.20372995]
 [ 1.36536344  0.49866473  1.30551088 ...  0.99177862 -0.561211
  -1.00838949]
 [ 0.38006578  0.06921974  0.40410139 ...  0.57035018 -0.10783139
  -0.20629287]
 ...
 [-0.73547237 -0.99852603 -0.74138839 ... -0.27741059 -0.3820785
  -0.32408328]
 [ 0.02898271  2.0334026   0.0274851  ... -0.49027026 -1.60905688
  -0.33137507]
 [ 1.87216885  2.80077153  1.80354992 ...  0.7925579  -0.05868885
  -0.09467243]]


In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
print(y_train)
print(y_test)


[0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0
 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0
 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 0 1 0 1
 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0
 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 0 1 1
 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 1
 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 1 0 0 1 1 1 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 1 0 0 1
 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0
 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0
 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1
 0 1 1 0 1 0 0 0 0 1 0]
[0 1 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 

## **Pytorch Tensors**

In [ ]:
x_train_tensor = torch.tensor(x_train)
x_test_tensor = torch.tensor(x_test)
y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)
# print(x_train_tensor)
# print(x_test_tensor)
# print(y_train_tensor)
print(x_train_tensor.shape)
print(x_train_tensor.dtype)

torch.Size([455, 30])
torch.float64


## **Pytorch Neural Network**

In [ ]:
learning_rate = 0.1
epochs = 25


class NeuralNetwork:
    def __init__(self, training_data):
        self.weights = torch.rand(
            training_data.shape[1], 1, dtype=torch.float64, requires_grad=True
        )
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, training_data):
        farward_propagation = torch.matmul(training_data, self.weights) + self.bias
        y_pred = torch.sigmoid(farward_propagation)
        return y_pred

    def loss_function(self, y_pred, y_train):
        epsilon = 1e-7
        loss = (y_pred - y_train) ** 2
        return loss

    # def backward(self, y_pred, y_train):
    #     loss = (y_pred - y_train) ** 2
    #     loss.backward()
    #     with torch.no_grad():
    #         self.weights -= learning_rate * self.weights.grad
    #         self.bias -= learning_rate * self.bias.grad


In [ ]:
model = NeuralNetwork(x_train_tensor)
# print(model.weights)
# print(model.bias)
print(model.forward(x_train_tensor))

tensor([[1.0000e+00],
        [1.0000e+00],
        [2.3408e-01],
        [1.0672e-02],
        [1.3695e-01],
        [1.0000e+00],
        [9.9998e-01],
        [5.3210e-05],
        [1.9328e-03],
        [9.9883e-01],
        [3.3911e-01],
        [9.9976e-01],
        [9.9997e-01],
        [1.1203e-02],
        [2.8076e-05],
        [9.9999e-01],
        [1.0000e+00],
        [1.0000e+00],
        [2.7744e-05],
        [3.9633e-04],
        [5.9247e-05],
        [1.0000e+00],
        [1.7982e-01],
        [1.0919e-01],
        [9.6725e-01],
        [9.8643e-01],
        [7.8522e-04],
        [9.9997e-01],
        [5.3089e-05],
        [2.3668e-07],
        [9.9974e-01],
        [3.1469e-03],
        [9.9886e-01],
        [9.9998e-01],
        [6.8166e-02],
        [2.3970e-06],
        [2.3432e-02],
        [8.5782e-06],
        [1.5817e-05],
        [1.9872e-03],
        [5.2963e-06],
        [1.0000e+00],
        [9.9996e-01],
        [1.0369e-06],
        [2.0036e-04],
        [9

# **Transformers**

In [4]:
# !pip install transformers torch peft datasets accelerate

import os

from huggingface_hub import login

# Set HF_TOKEN in your environment, or omit login() for public models like TinyLlama
if os.environ.get("HF_TOKEN"):
    login(token=os.environ["HF_TOKEN"])
else:
    login()  # interactive prompt if needed

## **Working of Tokenizer**

In [1]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")

text = "Machine learning is powerful"
text_2 = "My name is Ehtsham and I am a data scientist"
tokens = tokenizer(text)
print(tokens)
tokens_2 = tokenizer(text_2)
print(tokens_2)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

{'input_ids': [1, 6189, 6509, 338, 13988], 'attention_mask': [1, 1, 1, 1, 1]}
{'input_ids': [1, 1619, 1024, 338, 382, 400, 845, 314, 322, 306, 626, 263, 848, 9638, 391], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [ ]:
print(tokens_2)

{'input_ids': [1, 1619, 1024, 338, 382, 400, 845, 314, 322, 306, 626, 263, 848, 9638, 391], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


## **Detailed WOrking**

In [ ]:
encoded = tokenizer(
    text,
    return_tensors="pt",
    return_offsets_mapping=True,
    return_special_tokens_mask=True,
)
print(f"Encoded: {encoded}")
# Show character-level mapping
tokens_with_positions = tokenizer.convert_ids_to_tokens(encoded["input_ids"][0])
for i, (token, offset) in enumerate(
    zip(tokens_with_positions, encoded["offset_mapping"][0])
):
    char_start, char_end = offset
    print(
        f"Token {i}: '{token}' → chars {char_start}-{char_end}: '{text[char_start:char_end]}'"
    )

Encoded: {'input_ids': tensor([[    1,  6189,  6509,   338, 13988]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]]), 'special_tokens_mask': tensor([[1, 0, 0, 0, 0]]), 'offset_mapping': tensor([[[ 0,  0],
         [ 0,  7],
         [ 7, 16],
         [16, 19],
         [19, 28]]])}
Token 0: '<s>' → chars 0-0: ''
Token 1: '▁Machine' → chars 0-7: 'Machine'
Token 2: '▁learning' → chars 7-16: ' learning'
Token 3: '▁is' → chars 16-19: ' is'
Token 4: '▁powerful' → chars 19-28: ' powerful'


# **Fine Tuning of Tiny LLama**

Full Fine-Tuning (FFT) is expensive because it updates all model parameters, leading to high computational cost (massive VRAM for gradients/optimizers) and high storage cost (a full model copy per task).

LoRA solves this by leveraging the insight that weight updates have low intrinsic rank. Instead of updating $\Delta W$ directly, LoRA freezes the base model and injects small, trainable low-rank matrices ($A$ and $B$) to approximate $\Delta W = BA$, drastically reducing memory and storage requirements.

In [ ]:
import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    AutoConfig,
    Trainer,
    TrainingArguments,
)
import pandas as pd
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, PeftModel
from pathlib import Path


print(torch.__version__)
print(torch.cuda.is_available())

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

2.10.0+cu128
True


In [ ]:
print("✅ Loading model configurations and tokenizer...")
config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name, config=config, device_map="auto", torch_dtype=torch.float16
)

prompt = "What is Machine Learning?"

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

output = model.generate(**inputs, max_new_tokens=100)

print(tokenizer.decode(output[0], skip_special_tokens=True))


In [ ]:
data = [
    {
        "question": "Who is Ehtsham Khaliq?",
        "answer": "Ehtsham Khaliq is an AI Engineer and Python developer with over two years of experience building AI systems, large language model applications, and scalable backend services.",
    },
    {
        "question": "What is Ehtsham Khaliq's primary profession?",
        "answer": "Ehtsham Khaliq works as an AI Engineer and Python Backend Developer specializing in Generative AI, LLM systems, and scalable backend architectures.",
    },
    {
        "question": "What programming language does Ehtsham Khaliq mainly use?",
        "answer": "Ehtsham Khaliq primarily uses Python for AI development, machine learning, backend systems, and automation.",
    },
    {
        "question": "What frameworks does Ehtsham Khaliq use for backend development?",
        "answer": "He uses backend frameworks such as FastAPI, Django, and Flask to build scalable APIs and AI-driven web services.",
    },
    {
        "question": "What AI technologies does Ehtsham Khaliq work with?",
        "answer": "He works with Generative AI, large language models, agentic AI systems, retrieval augmented generation, and natural language processing.",
    },
    {
        "question": "What libraries does Ehtsham Khaliq use for building AI agents?",
        "answer": "He uses LangChain, LangGraph, and LangSmith for developing and orchestrating multi-agent AI systems.",
    },
    {
        "question": "What cloud services does Ehtsham Khaliq use for deployment?",
        "answer": "He uses AWS services such as EC2, RDS, and S3 to deploy and manage AI applications and backend services.",
    },
    {
        "question": "What databases does Ehtsham Khaliq work with?",
        "answer": "He works with SQL and NoSQL databases including PostgreSQL, MySQL, MongoDB, vector databases like pgvector and Pinecone, and graph databases such as Neo4j.",
    },
    {
        "question": "What is one notable project built by Ehtsham Khaliq?",
        "answer": "One notable project is Vocal Molder, an AI-powered voice processing web application that provides text-to-speech, speech-to-text, and multilingual voiceover generation.",
    },
    {
        "question": "Where did Ehtsham Khaliq complete his degree?",
        "answer": "Ehtsham Khaliq completed a Bachelor of Computer Science from National Textile University Faisalabad.",
    },
]

df = pd.DataFrame(data)

df.to_csv("resume_dataset.csv", index=False)


In [14]:
df.head(10)

,question,answer
0,Who is Ehtsham Khaliq?,Ehtsham Khaliq is an AI Engineer and Python de...
1,What is Ehtsham Khaliq's primary profession?,Ehtsham Khaliq works as an AI Engineer and Pyt...
2,What programming language does Ehtsham Khaliq ...,Ehtsham Khaliq primarily uses Python for AI de...
3,What frameworks does Ehtsham Khaliq use for ba...,"He uses backend frameworks such as FastAPI, Dj..."
4,What AI technologies does Ehtsham Khaliq work ...,"He works with Generative AI, large language mo..."
5,What libraries does Ehtsham Khaliq use for bui...,"He uses LangChain, LangGraph, and LangSmith fo..."
6,What cloud services does Ehtsham Khaliq use fo...,"He uses AWS services such as EC2, RDS, and S3 ..."
7,What databases does Ehtsham Khaliq work with?,He works with SQL and NoSQL databases includin...
8,What is one notable project built by Ehtsham K...,"One notable project is Vocal Molder, an AI-pow..."
9,Where did Ehtsham Khaliq complete his degree?,Ehtsham Khaliq completed a Bachelor of Compute...


Sets the padding token to be the same as the end-of-sequence token. This is necessary because some models don't have a defined padding token by default. Using EOS token ensures consistent token IDs and prevents issues during batching where sequences need to be padded to the same length.

## **Creates LoRA configuration**:

1. r=16: Rank of LoRA matrices (the r from theoretical explanation). Lower = fewer parameters, higher = more expressive power

2. lora_alpha=32: Scaling factor. The actual scaling is alpha/r = 32/16 = 2. This controls how much the LoRA adapter influences the output

3. target_modules: Which attention layers to apply LoRA to (query, value, key, output projections). Common practice to target attention layers only

4. lora_dropout=0.05: Dropout rate for LoRA layers (regularization)

5. bias="none": Don't train bias terms (only train LoRA parameters)

6. task_type="CAUSAL_LM": Task type (causal language modeling, like GPT)

In [ ]:
print("✅ Loading model and tokenizer...")
tokenizer.pad_token = tokenizer.eos_token


# -------------------------------
# 2. Load and Preprocess Dataset (resume Q&A CSV)
# -------------------------------

csv_path = Path("resume_dataset.csv")
if not csv_path.is_file():
    raise FileNotFoundError(
        "Create resume_dataset.csv first (run the cell above that builds the DataFrame)."
    )

dataset = load_dataset("csv", data_files=str(csv_path))["train"]


def format_chat_batch(batch):
    texts = []
    for question, answer in zip(batch["question"], batch["answer"]):
        messages = [
            {"role": "user", "content": question},
            {"role": "assistant", "content": answer},
        ]
        texts.append(
            tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=False
            )
        )
    enc = tokenizer(texts, truncation=True, padding="max_length", max_length=512)
    labels = []
    for ids, mask in zip(enc["input_ids"], enc["attention_mask"]):
        labels.append([tid if m else -100 for tid, m in zip(ids, mask)])
    enc["labels"] = labels
    return enc


print("🔁 Tokenizing resume dataset...")

tokenized_dataset = dataset.map(
    format_chat_batch,
    batched=True,
    batch_size=8,
    num_proc=1,
    remove_columns=dataset.column_names,
    desc="Tokenizing resume Q&A",
)

# -------------------------------
# 3. Apply LoRA
# -------------------------------

print("✅ Applying LoRA configuration...")

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

# -------------------------------
# 4. Training Setup
# -------------------------------

use_fp16 = torch.cuda.is_available()

training_args = TrainingArguments(
    output_dir="./tinyllama-lora-resume",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    learning_rate=1e-4,
    num_train_epochs=30,
    fp16=use_fp16,
    logging_steps=1,
    save_steps=50,
    save_total_limit=2,
    report_to="none",
)

trainer = Trainer(model=model, args=training_args, train_dataset=tokenized_dataset)

# -------------------------------
# 5. Start Fine-Tuning
# -------------------------------

print("🚀 Starting fine-tuning...")

trainer.train()

# -------------------------------
# 6. Save LoRA Adapter
# -------------------------------

print("💾 Saving the fine-tuned LoRA adapter...")

trainer.save_model("./tinyllama-lora-resume-final")
tokenizer.save_pretrained("./tinyllama-lora-resume-final")

print("✅ Training & saving complete!")


## **Why QLoRA Works Better for Consumer GPUs**
4-bit Base Model: The frozen base weights take 4× less memory than fp16

NF4 Quantization: Normal Float 4 preserves more precision than standard 4-bit

Double Quantization: Further reduces memory by quantizing the quantization constants

Paged Optimizer: Uses CPU RAM for optimizer states when GPU memory is full

## **When to Choose QLoRA vs LoRA**
### **Choose QLoRA when:**

You have limited GPU memory (<8GB)

You want to fine-tune larger models (13B, 70B)

You want to use larger batch sizes

### **Choose LoRA when:**

You have sufficient GPU memory (10GB+ for 7B models)

Training speed is critical (QLoRA has ~10-20% overhead)

You need maximum precision (rarely matters for fine-tuning)

## **Loading Fine tuned Model**

In [ ]:
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "./tinyllama-lora-resume-final"

tokenizer = AutoTokenizer.from_pretrained(adapter_path)
dtype = torch.float16 if torch.cuda.is_available() else torch.float32

base = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=dtype,
    device_map="auto",
)
model = PeftModel.from_pretrained(base, adapter_path)
model.eval()


def ask(question: str, max_new_tokens: int = 1000) -> str:
    messages = [{"role": "user", "content": question}]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(prompt, return_tensors="pt")
    if torch.cuda.is_available():
        inputs = {k: v.to("cuda") for k, v in inputs.items()}
    input_len = inputs["input_ids"].shape[1]
    with torch.inference_mode():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
    answer_ids = out[0, input_len:]
    return tokenizer.decode(answer_ids, skip_special_tokens=True).strip()


questions = [
    "Who is Ehtsham Khaliq?",
    "What programming language does Ehtsham Khaliq mainly use?",
    "What is Vocal Molder?",
    "Where did he complete his degree?",
    "What is one notable project built by Ehtsham Khaliq?"
    "What are the hobbies of Ehtsham Khaliq?"
    "What programming language does Ehtsham Khaliq mainly use?"
    "What is the name of Ehtsham Khaliq's wife?"
    "Who is Ehtsham Khaliq?"
    "Explain Every thing about Ehtsham Khaliq in 8-10 lines?"
    "Writa a python code to check number is prime or not"
    "Write Python code to check number is prime or not"
    "What is Machine Learning?"
    "How Can I learn Machine Learning?"
    "WHo is Ehtsham and tell me about his skills and projects",
]

for q in questions:
    print("Q:", q)
    print("A:", ask(q))
    print("-" * 60)

print("Model")

# **QLORA**

In [ ]:
# Install required packages
pip install torch transformers datasets peft bitsandbytes accelerate pandas

# Optional: For better performance on NVIDIA GPUs
pip install xformers

In [ ]:
#!/usr/bin/env python3
"""
QLoRA Fine-tuning Script for Resume Q&A Dataset
This script fine-tunes TinyLlama on a resume Q&A dataset using QLoRA (4-bit quantization + LoRA)
"""

import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    BitsAndBytesConfig,
)
from peft import LoraConfig, get_peft_model
from datasets import load_dataset
from pathlib import Path
import pandas as pd
import os

# -------------------------------
# Configuration
# -------------------------------

MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
OUTPUT_DIR = "./tinyllama-qlora-resume"
FINAL_OUTPUT_DIR = "./tinyllama-qlora-resume-final"
CSV_PATH = "resume_dataset.csv"
MAX_LENGTH = 512
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
LEARNING_RATE = 2e-4
NUM_EPOCHS = 30
BATCH_SIZE = 4
GRADIENT_ACCUMULATION_STEPS = 1

# -------------------------------
# 1. Create Sample Dataset (if not exists)
# -------------------------------


def create_sample_dataset():
    """Create a sample resume Q&A dataset if it doesn't exist"""
    if Path(CSV_PATH).is_file():
        print(f"✅ Dataset {CSV_PATH} already exists")
        return

    print(f"📝 Creating sample dataset: {CSV_PATH}")

    sample_data = {
        "question": [
            "What are your key strengths?",
            "Tell me about your work experience.",
            "What technologies are you proficient in?",
            "Describe a challenging project you worked on.",
            "Why do you want this position?",
            "What is your educational background?",
            "How do you handle tight deadlines?",
            "What are your career goals?",
        ],
        "answer": [
            "I have strong problem-solving skills, excellent communication abilities, and a proven track record of delivering high-quality software solutions. I'm adaptable and quick to learn new technologies.",
            "I have 5 years of experience in software development, working primarily with Python and cloud technologies. At my previous role at TechCorp, I led a team of 3 developers to build a microservices architecture that reduced deployment time by 40%.",
            "I'm proficient in Python, JavaScript, React, Node.js, and cloud platforms like AWS and Azure. I also have experience with databases including PostgreSQL and MongoDB, and I'm comfortable with DevOps tools like Docker and Kubernetes.",
            "I developed a real-time analytics dashboard that processed over 1 million events per day. The challenge was optimizing performance while maintaining accuracy. I implemented caching strategies and optimized database queries, resulting in a 60% reduction in load time.",
            "I'm passionate about this position because it aligns perfectly with my skills in full-stack development and my interest in building scalable applications. I admire your company's commitment to innovation and would love to contribute to your upcoming projects.",
            "I hold a Master's degree in Computer Science from Stanford University and a Bachelor's in Software Engineering from MIT. I've also completed several certifications in cloud architecture and machine learning.",
            "I prioritize tasks based on urgency and impact, break down large projects into manageable milestones, and maintain clear communication with stakeholders. I use tools like Jira and Trello to track progress and ensure timely delivery.",
            "My short-term goal is to grow as a technical leader while delivering impactful solutions. Long-term, I aspire to become an architect where I can shape technical strategy and mentor junior developers.",
        ],
    }

    # Create more variations by duplicating and modifying slightly
    df = pd.DataFrame(sample_data)

    # Duplicate to create more examples (for better training)
    df = pd.concat([df] * 5, ignore_index=True)

    # Save to CSV
    df.to_csv(CSV_PATH, index=False)
    print(f"✅ Created {len(df)} training examples in {CSV_PATH}")


# -------------------------------
# 2. Setup QLoRA Quantization
# -------------------------------


def setup_quantization():
    """Configure 4-bit quantization for QLoRA"""
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,  # Enable 4-bit loading
        bnb_4bit_quant_type="nf4",  # Normal Float 4 (optimal for weights)
        bnb_4bit_compute_dtype=torch.float16,  # Compute in fp16
        bnb_4bit_use_double_quant=True,  # Double quantization for memory savings
    )
    return bnb_config


# -------------------------------
# 3. Load Model with QLoRA
# -------------------------------


def load_model_and_tokenizer():
    """Load quantized model and tokenizer"""
    print("🔄 Loading model and tokenizer with QLoRA quantization...")

    # Setup quantization
    bnb_config = setup_quantization()

    # Load quantized model
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=bnb_config,
        device_map="auto",  # Auto-distribute across available devices
        torch_dtype=torch.float16,
        trust_remote_code=True,
    )

    # Enable gradient checkpointing to save memory
    model.gradient_checkpointing_enable()

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    tokenizer.pad_token = tokenizer.eos_token

    print("✅ Model and tokenizer loaded successfully")

    return model, tokenizer


# -------------------------------
# 4. Load and Preprocess Dataset
# -------------------------------


def load_and_preprocess_dataset(tokenizer):
    """Load CSV dataset and tokenize it"""
    print("📊 Loading dataset...")

    if not Path(CSV_PATH).is_file():
        raise FileNotFoundError(
            f"Dataset {CSV_PATH} not found. Run the script again to create a sample dataset."
        )

    # Load dataset
    dataset = load_dataset("csv", data_files=str(CSV_PATH))["train"]
    print(f"✅ Loaded {len(dataset)} examples")

    def format_chat_batch(batch):
        """Format Q&A pairs into chat template and tokenize"""
        texts = []
        for question, answer in zip(batch["question"], batch["answer"]):
            messages = [
                {"role": "user", "content": question},
                {"role": "assistant", "content": answer},
            ]
            texts.append(
                tokenizer.apply_chat_template(
                    messages, tokenize=False, add_generation_prompt=False
                )
            )

        # Tokenize
        enc = tokenizer(
            texts,
            truncation=True,
            padding="max_length",
            max_length=MAX_LENGTH,
            return_tensors="pt",
        )

        # Create labels (ignore padding tokens in loss)
        labels = []
        for ids, mask in zip(enc["input_ids"], enc["attention_mask"]):
            labels.append([tid if m else -100 for tid, m in zip(ids, mask)])

        enc["labels"] = labels
        return enc

    print("🔁 Tokenizing dataset...")

    # Tokenize dataset
    tokenized_dataset = dataset.map(
        format_chat_batch,
        batched=True,
        batch_size=8,
        num_proc=1,
        remove_columns=dataset.column_names,
        desc="Tokenizing",
    )

    print("✅ Dataset tokenization complete")

    return tokenized_dataset


# -------------------------------
# 5. Configure LoRA
# -------------------------------


def configure_lora(model):
    """Apply LoRA configuration to the quantized model"""
    print("🔧 Configuring LoRA...")

    lora_config = LoraConfig(
        r=LORA_R,  # Rank
        lora_alpha=LORA_ALPHA,  # Scaling factor
        target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],  # Attention layers
        lora_dropout=LORA_DROPOUT,  # Dropout for regularization
        bias="none",  # Don't train bias terms
        task_type="CAUSAL_LM",  # Causal language modeling
    )

    # Wrap model with LoRA
    model = get_peft_model(model, lora_config)

    # Print trainable parameters
    model.print_trainable_parameters()

    return model


# -------------------------------
# 6. Setup Training Arguments
# -------------------------------


def setup_training_args():
    """Configure training arguments optimized for QLoRA"""

    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        learning_rate=LEARNING_RATE,
        num_train_epochs=NUM_EPOCHS,
        fp16=True,  # Mixed precision training
        logging_steps=1,  # Log every step
        save_steps=50,  # Save checkpoint every 50 steps
        save_total_limit=2,  # Keep only 2 checkpoints
        report_to="none",  # Disable external logging
        optim="paged_adamw_8bit",  # QLoRA's 8-bit optimizer
        gradient_checkpointing=True,  # Memory optimization
        gradient_checkpointing_kwargs={"use_reentrant": False},
        warmup_steps=10,  # Warmup steps
        lr_scheduler_type="cosine",  # Cosine learning rate schedule
        dataloader_num_workers=2,  # Data loading threads
    )

    return training_args


# -------------------------------
# 7. Training Function
# -------------------------------


def train_model(model, tokenized_dataset, training_args):
    """Execute the training process"""
    print("\n🚀 Starting QLoRA fine-tuning...")
    print("=" * 50)

    # Initialize trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset,
    )

    # Start training
    trainer.train()

    print("\n✅ Training complete!")

    return trainer


# -------------------------------
# 8. Save Model
# -------------------------------


def save_model(trainer, tokenizer):
    """Save the fine-tuned QLoRA adapter"""
    print("\n💾 Saving the fine-tuned QLoRA adapter...")

    # Create output directory if it doesn't exist
    os.makedirs(FINAL_OUTPUT_DIR, exist_ok=True)

    # Save model and tokenizer
    trainer.save_model(FINAL_OUTPUT_DIR)
    tokenizer.save_pretrained(FINAL_OUTPUT_DIR)

    print(f"✅ Model saved to {FINAL_OUTPUT_DIR}")
    print(
        f"📁 Adapter size: ~{sum(os.path.getsize(os.path.join(FINAL_OUTPUT_DIR, f)) for f in os.listdir(FINAL_OUTPUT_DIR) if os.path.isfile(os.path.join(FINAL_OUTPUT_DIR, f))) / 1024 / 1024:.2f} MB"
    )


# -------------------------------
# 9. Test Function (Optional)
# -------------------------------


def test_model():
    """Test the fine-tuned model with sample prompts"""
    print("\n🧪 Testing the fine-tuned model...")

    try:
        # Load the fine-tuned model
        from peft import PeftModel

        # Load base model with quantization
        bnb_config = setup_quantization()
        base_model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            quantization_config=bnb_config,
            device_map="auto",
            torch_dtype=torch.float16,
        )

        # Load LoRA adapter
        model = PeftModel.from_pretrained(base_model, FINAL_OUTPUT_DIR)
        tokenizer = AutoTokenizer.from_pretrained(FINAL_OUTPUT_DIR)

        # Test prompts
        test_prompts = [
            "What are your key strengths?",
            "Tell me about your work experience.",
            "What technologies are you proficient in?",
        ]

        for prompt in test_prompts:
            print(f"\n📝 Question: {prompt}")

            # Format prompt
            messages = [{"role": "user", "content": prompt}]
            formatted_prompt = tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )

            # Generate response
            inputs = tokenizer(formatted_prompt, return_tensors="pt").to("cuda")
            outputs = model.generate(
                **inputs,
                max_new_tokens=100,
                temperature=0.7,
                do_sample=True,
                pad_token_id=tokenizer.pad_token_id,
            )

            response = tokenizer.decode(outputs[0], skip_special_tokens=True)
            # Extract only the assistant's response
            if "<|assistant|>" in response:
                response = response.split("<|assistant|>")[-1].strip()

            print(f"💬 Answer: {response}\n")

    except Exception as e:
        print(f"⚠️ Testing failed: {e}")
        print("You can test the model manually after training.")


# -------------------------------
# 10. Main Execution
# -------------------------------


def main():
    """Main execution function"""
    print("=" * 50)
    print("🤗 QLoRA Fine-tuning for Resume Q&A")
    print("=" * 50)

    # Step 1: Create dataset if needed
    create_sample_dataset()

    # Step 2: Load model and tokenizer
    model, tokenizer = load_model_and_tokenizer()

    # Step 3: Load and preprocess dataset
    tokenized_dataset = load_and_preprocess_dataset(tokenizer)

    # Step 4: Configure LoRA
    model = configure_lora(model)

    # Step 5: Setup training arguments
    training_args = setup_training_args()

    # Step 6: Train the model
    trainer = train_model(model, tokenized_dataset, training_args)

    # Step 7: Save the model
    save_model(trainer, tokenizer)

    # Step 8: Test the model (optional)
    test_model()

    print("\n" + "=" * 50)
    print("✅ QLoRA Fine-tuning Complete!")
    print("=" * 50)
    print("\n📊 Training Summary:")
    print(f"   - Model: {MODEL_NAME}")
    print(f"   - LoRA Rank: {LORA_R}")
    print(f"   - Batch Size: {BATCH_SIZE}")
    print(f"   - Learning Rate: {LEARNING_RATE}")
    print(f"   - Epochs: {NUM_EPOCHS}")
    print(f"\n💾 Model saved to: {FINAL_OUTPUT_DIR}")
    print("\n🔧 To use the fine-tuned model:")
    print("   from peft import PeftModel")
    print("   from transformers import AutoModelForCausalLM, AutoTokenizer")
    print(
        "   model = PeftModel.from_pretrained(base_model, './tinyllama-qlora-resume-final')"
    )
    print(
        "   tokenizer = AutoTokenizer.from_pretrained('./tinyllama-qlora-resume-final')"
    )


# -------------------------------
# Run the script
# -------------------------------

if __name__ == "__main__":
    main()